### ISSUE TITLE
ValueError: node array from the pickle has an incompatible dtype

### ISSUE THREAD

**Issue by vladimirkovacevic** [raghavagps/toxinpred3#1]
I installed toxinpred3 with:
```
pip install toxinpred3
```
And after running:
```
toxinpred3 -i merged_nontoxic_peptides_10.fa
```
Got an error:
```
Summary of Parameters:
Input File:  data/tox/merged_nontoxic_peptides_100.fa ; Model:  2 ; Threshold:  0.38
Output File:  outfile.csv ; Display:  2
Traceback (most recent call last):
  File "/Users/vladimirk/opt/anaconda3/bin/toxinpred3", line 8, in <module>
    sys.exit(main())
  File "/Users/vladimirk/opt/anaconda3/lib/python3.9/site-packages/toxinpred3/python_scripts/toxinpred3.py", line 364, in main
    prediction('seq.aac', 'seq.dpc', nf_path+'/../model/toxinpred3.0_model.pkl','seq.pred')
  File "/Users/vladimirk/opt/anaconda3/lib/python3.9/site-packages/toxinpred3/python_scripts/toxinpred3.py", line 81, in prediction
    clf = joblib.load(file_name2)
  File "/Users/vladimirk/opt/anaconda3/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/vladimirk/opt/anaconda3/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/Users/vladimirk/opt/anaconda3/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/Users/vladimirk/opt/anaconda3/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 402, in load_build
    Unpickler.load_build(self)
  File "/Users/vladimirk/opt/anaconda3/lib/python3.9/pickle.py", line 1717, in load_build
    setstate(state)
  File "sklearn/tree/_tree.pyx", line 728, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1432, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
```
merged_nontoxic_peptides_10.fa:
```
>nontoxic_hemolytik_1
RWKIFKKIEKVGRNVRDGIIKAGPAVAVVGQAATVVKG
>nontoxic_hemolytik_4;nontoxic_DBAASP_284
VSAVAKVAMKKGAALLKKMGVKISPLK
>nontoxic_hemolytik_5;nontoxic_DBAASP_285
KQLKKVSAVAKVAMKKGAALLKKMGVK
>nontoxic_hemolytik_6;nontoxic_DBAASP_286
VGKVLKQLKKVSAVAKVAMKKGAALLK
>nontoxic_hemolytik_7;nontoxic_DBAASP_287
KFGKIVGKVLKQLKKVSAVAKVAMKKG
```
My pickle version is 4.0. Do you know how can I fix this error?

**Comment by anandr88** [comment]
The error you're encountering is due to scikit-learn Versions. Please use
 !pip install scikit-learn==1.0.2

**Comment by vladimirkovacevic** [comment]
Thank you for the prompt response. Downgrading scikit-learn would solve the issue but please consider fixing this in more systematic way.
